version: '3'

services:
  app:
    build: 
      context: ./app/
    restart: always
    ports:
      - 5000:5000
    environment:
      MYSQL_USER: weather
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: weather
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    links:
      - database
  database:
    image: mariadb:${MARIA_VERSION}
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: weather
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /home/eg/Pile/docker-test/db:/docker-entrypoint-initdb.d      
  test: 
    build: 
      context: ./app/
      dockerfile: Dockerfile.test
    environment:
      MYSQL_USER: weather
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: weather
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    command: ["python", "-m", "unittest", "test.py"]