version: '3'

services:
  app:
    build: 
      context: ./app/
    volumes:
      - ./app:/code
    restart: always
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: weather
      MYSQL_PASS: ${MYSQL_PASS}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      BOOT_DELAY: 20
    depends_on:
      - database
  database:
    image: mariadb:${MARIA_VERSION}
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: weather
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /home/eg/Pile/docker-test/db:/docker-entrypoint-initdb.d      
  test: 
    build: 
      context: ./app/
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/code
    depends_on:
      - database
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: weather
      MYSQL_PASS: ${MYSQL_PASS}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      BOOT_DELAY: 20
    command: ["python", "-m", "unittest", "test.py"]
  web:
    image: nginx
    volumes:
      - ./web/conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    ports:
      - 5000:80
    depends_on:
      - app    
    command: [nginx-debug, '-g', 'daemon off;']
    