FROM python:3.8 as builder
COPY requirements.txt .
RUN pip install --user -r requirements.txt


FROM python:3.8-slim
WORKDIR /code

COPY --from=builder /root/.local /root/.local
COPY . .
COPY test.py .

ENV PATH=/root/.local:$PATH


CMD ["python", "-m", "unittest", "test.py"]